---
title: "Memo"
toc: false
output: 
        pdf_document:
                extra_dependencies: ["float"]
---

Potential to model only childlessness by states or race or both

# Functional form

* Candidates: Richards, Janoschek, Logistic

* Generalized logistic (Richards) curve with only an additional parameter for the lower asymptote seems to do a good job.

* Try optimizing with optim()

# Data

* Info on States available in CPS?

* HFD protocol on exposure per parity

* Back of the envelope calculation accounting for parity

$$\sum_x P_x \cdot M_x \cdot (\sum^5_j p_j\cdot j)$$

* Define potential project on NSFG data

    * 2006-2019 NSFG data
    
    * Race, Age (in 5 years?)
    
    * Geography?
    
    * Metrics of interest: childlessness at end of reproduction, variance in probability of childless
    
    * Modeling opportunity? (ie Multinomial with parametric forms on the ps)


* Modeling: multinomial with model on ps, over time, by age, sex (and geographical location) + focus on childlessness 




